//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReportDrillDown
    {
        public string STORE_BRANCH { get; set; }
        public string SERIAL_ { get; set; }
        public string FitzWayVIN { get; set; }
        public string STOCK_ { get; set; }
        public string NEW_USED { get; set; }
        public Nullable<int> ChromeStyleID { get; set; }
        public Nullable<int> YEAR { get; set; }
        public string MAKE { get; set; }
        public string CARLINE { get; set; }
        public Nullable<int> DAYS_IN_STOCK { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<decimal> BASE_MSRP { get; set; }
        public Nullable<decimal> INVOICE { get; set; }
        public Nullable<decimal> INVEN_AMT { get; set; }
        public Nullable<int> STAT_CODE { get; set; }
        public string LOCATION { get; set; }
        public string EXT_COLOR { get; set; }
        public string INT_COLOR { get; set; }
        public Nullable<int> CustomPhotos { get; set; }
        public string ChromeOptions { get; set; }
        public int Id_Primary { get; set; }
    }
}
