//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryNotOnFitzMall_Report
    {
        public string STOREBRANCH { get; set; }
        public string LOCATION { get; set; }
        public string MAKE { get; set; }
        public Nullable<int> ShouldBeOnWebSite_1 { get; set; }
        public Nullable<int> ShouldBeOnWebSite_2 { get; set; }
        public Nullable<int> ShouldBeOnWebSite_4 { get; set; }
        public Nullable<int> ShouldBeOnWebSite_9 { get; set; }
        public Nullable<int> ShouldBeOnWebSite_12 { get; set; }
        public Nullable<int> ShouldBeOnWebSite_14 { get; set; }
        public Nullable<int> FM_TotalAllCarStat { get; set; }
        public Nullable<int> ActuallyOnWebSite_1 { get; set; }
        public Nullable<int> ActuallyOnWebSite_2 { get; set; }
        public Nullable<int> ActuallyOnWebSite_4 { get; set; }
        public Nullable<int> ActuallyOnWebSite_9 { get; set; }
        public Nullable<int> ActuallyOnWebSite_12 { get; set; }
        public Nullable<int> ActuallyOnWebSite_14 { get; set; }
        public Nullable<int> ActuallyOnWebSite_TotalAllCarStat { get; set; }
        public int Id_Primary { get; set; }
    }
}
