//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportInventory
    {
        public string NEWUSED { get; set; }
        public string STOREBRANCH { get; set; }
        public string LOCATION { get; set; }
        public string MAKE { get; set; }
        public Nullable<int> CarStat1 { get; set; }
        public Nullable<int> CarStat2 { get; set; }
        public Nullable<int> CarStat4 { get; set; }
        public Nullable<int> CarStat9 { get; set; }
        public Nullable<int> CarStat12 { get; set; }
        public Nullable<int> CarStat14 { get; set; }
        public Nullable<int> TotalAllCarStat { get; set; }
        public int Id_Primary { get; set; }
    }
}
