//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreBranchByALLLocation
    {
        public string STORE_BRANCH { get; set; }
        public string LOCATION { get; set; }
        public string LOCATION2 { get; set; }
        public int Id_Primary { get; set; }
    }
}
